### ISSUE TITLE
CSS Styling: Navigation components

### ISSUE THREAD

**Issue by kappanjoe** [OriOri-CCP7/oriori#62]
- [x] Basic CSS layout for:
  - [x] Navbar component
  - [x] Header component

**Comment by SirrorsMoore1975** [comment]
narbar's icon has resized according with px instead of %. 
This way when the screen width changes size, it does not expend with the screen size width. 

I setup three different screen size:
less than 320px referred as small, 
321px-768px referred as medium, and  
bigger than 769px referred as large.

Although I refer it as 'small medium large', the px size decrease as the screen width get larger.

Do you needed the <Narbar> to be lying above the <Footer>, or does it look fine if it is just hover above the <Footer>?

**Comment by kappanjoe** [comment]
> Do you needed the to be lying above the
> 
> , or does it look fine if it is just hover above the ?

Sorry, not sure I understand this question. If you are still seeking an answer to this Q, could you rephrase please?
